---
- name: Copy file of docker-compose
  ansible.builtin.template:
    src: "docker-compose.j2"
    dest:  "{{ root_dir }}/docker-compose.yaml"

- name: Copy config file of Clickhouse
  ansible.builtin.template:
    src: "config.j2"
    dest: "{{ conf_dir }}/{{ item[1] }}/config.xml"
  with_items:
    - "{{ click_containers }}"

- name: Copy file of cluster structure
  ansible.builtin.template:
    src: "cluster_structure.j2"
    dest: "{{ conf_dir }}/{{ item[1] }}/config.d/cluster_structure.xml"
  with_items:
    - "{{ click_containers }}"

- name: Copy file of Zookeeper structure
  ansible.builtin.template:
    src: "zoo_structure.j2"
    dest: "{{ conf_dir }}/{{ item[1] }}/config.d/zoo_structure.xml"
  with_items:
    - "{{ click_containers }}"

- name: Copy file of Clickhouse users
  ansible.builtin.template:
    src: "users.j2"
    dest: "{{ conf_dir }}/{{ item[1] }}/users.xml"
  with_items:
    - "{{ click_containers }}"
