---
- name: Install Clickhouse to node of cluster  
  hosts: clickhouse
  become: true
  vars:
    root_dir: /opt/clickhouse-server

  roles:
    - click-structure
  tasks:
    - name: Run containers
      shell:
        cmd: "docker-compose -f docker-compose.yaml up -d"
        chdir: "{{ root_dir }}"

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ 9000 + item[0] }}"
      with_items:
        - "{{ click_containers }}"
